frr version 8.5
frr defaults traditional
hostname edge1
no ipv6 forwarding
!
interface lo
 ip address 10.0.0.254/32
!
interface eth1
 ip address 10.2.0.1/31
!
router bgp 65200
 bgp router-id 10.0.0.254
 no bgp default ipv4-unicast
 neighbor 10.2.0.0 remote-as 65001
 neighbor 10.2.0.0 description spine1
 !
 address-family ipv4 unicast
  neighbor 10.2.0.0 activate
  network 10.0.0.254/32
  network 8.8.8.0/24
 exit-address-family
!
ip route 8.8.8.0/24 Null0
!
line vty
!